// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteIDInput struct {
	ID string `json:"ID"`
}

type Pokemon struct {
	ID          string   `json:"ID"`
	Name        string   `json:"Name"`
	Description string   `json:"Description"`
	Category    string   `json:"Category"`
	Type        string   `json:"Type"`
	Abilities   []string `json:"Abilities"`
}

type PokemonCreateInput struct {
	ID          *string  `json:"ID"`
	Name        string   `json:"Name"`
	Description string   `json:"Description"`
	Category    string   `json:"Category"`
	Type        string   `json:"Type"`
	Abilities   []string `json:"Abilities"`
}

type PokemonUpdateInput struct {
	ID        string `json:"ID"`
	UpdateKey string `json:"UpdateKey"`
	UpdateVal string `json:"UpdateVal"`
}
